### ISSUE TITLE
port 8545 not opened in agora.sh

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/agora-chain#24]
docker-compose.yml file refers to port 8545, but agora.sh file does not.

i couldnt find port 8545 with running el-node with agora.sh  (sudo netstat -tulpn | grep LISTEN)

shouldnt agora.sh be like this? :
-p 30303:30303 -p 30303:30303/udp -p 8545:8545 \

**Comment by MichaelKim20** [comment]
PRs are merged #27 #26
