### ISSUE TITLE
Prometheus port 8081

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/agora-chain#33]
Hi,
Prometheus scrapes port 8081, see the documentation:
https://agora-cl-docs.bosagora.org/docs/agora-cl-usage/monitoring/grafana-dashboard

scrape_configs:
  - job_name: 'validator'
    static_configs:
      - targets: ['localhost:8081']

When i open port 8081 on agora-cl-validator there are no metrics.
Where is port 8081?
Port 8080 for agora-cl-node works fine.

**Comment by MichaelKim20** [comment]
This feature was added.

**Comment by RoscoPColtrane1** [comment]
Thank you Michael.
Have you tested this? just opening port 6060 isnt enough.
I also had to add this for my agora-el-node docker-compose file:
 --pprof
 --pprof.addr=0.0.0.0
 --pprof.port=6060

And had to config my prometheus.yml like this :
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'validator'
    static_configs:
      - targets: ['localhost:8081']
  - job_name: 'agora node'
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'agora-el-node'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets: ['localhost:6060']

Now i finally see some data in grafana :)
