### ISSUE TITLE
Mainnet Genesis state has not been created?

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/agora-chain#37]
I started on mainnet with first validator. but i get genesis errors

- i did a .'/agora.sh el-node init'. first.
- Validator is imported into the wallet, i'm ready for deposit on mainnet. (no deposid is made yet)
- Agora-el-node is synced till latest block. 

curl http://localhost:8080/healthz gives me these erors:
*initialsync.Service: OK
*builder.Service: OK
*rpc.Service: ERROR, syncing
*gateway.Gateway: OK
*p2p.Service: OK
*execution.Service: OK
*attestations.Service: OK
*blockchain.Service: ERROR, genesis state has not been created
*sync.Service: OK
*prometheus.Service: OK

docker logs agora-cl-node:
time="2022-12-04 16:58:26" level=info msg="Currently waiting for chainstart" Additional validators needed=1022 Generating genesis state in=711h59m47s prefix=powchain

docker logs agora-cl-validator:
time="2022-12-04 16:04:10" level=info msg="Syncing with beacon node to align on chain genesis info" prefix=validator

curl http://localhost:3500/eth/v1/node/syncing | jq   :
{
  "data": {
    "head_slot": "0",
    "sync_distance": "0",
    "is_syncing": true,
    "is_optimistic": false
  }
}

How do i know genesis syncing is ok on mainnet?

**Comment by RoscoPColtrane1** [comment]
These validators did a deposid but are still pending (this is not me):
https://agorascan.io/validator/0xae659a2034bd559448e2c65b485089698469e7b41d2788f191aaed347690bf90609869d74c88cd4d5f33bb9b574afb81#deposits
https://agorascan.io/validator/0xaef46791047f11e5396f3cb9820047321f64b6a4cb8aa4f405a9ecabf4d1fed45b27ff803f44a242b296a228a23abcd2#deposits

Im afraid to get penalties if i do a deposit and there is no chainstart.
I do not have this issue on testnet.

**Comment by MichaelKim20** [comment]
Agora-el is the mainnet's POA chain.
Agora-cl is the mainnet's POS chain.
The POS chain starts at 10 o'clock on January 10, 2023.
See) https://github.com/bosagora/agora-chain/blob/mainnet/root/config/cl/chain-config.yaml#L19-L20

Complete transition to POS chain will be completed after 9 February 2023

**Comment by RoscoPColtrane1** [comment]
Thanks, it would be good if this is communicated more clearly by the marketing team. People think POS is live now. 
So what happens if people deposit now? It keeps pending till after 9 february?

**Comment by MichaelKim20** [comment]
From January 10, 2023, validators can receive rewards.
From February 9, 2023, the BOSagora chain is changed to a fully decentralized network.

The conditions under which the block begins on January 10, 2023 are as follows:
timestamp : 1673312400
Number of validators: 1024 or higher

You can deposit it to become a validator on the mainnet now. When you make a deposit, do [here](https://agora-staking.bosagora.org)
And you just have to run the node and the validator before January 10, 2023(timestamp : 1673312400).

The POS chain starts counting down from the moment the number of validators reaches 1024.
And at the specified time (1673312400), they connect together and create a Genesis block.

**Comment by MichaelKim20** [comment]
Now is the time for users who will be validators to deposit in the BOSagora network and prepare for node operation.

**Comment by MichaelKim20** [comment]
If the following screen appears after you run Agora-cl, you have executed it normally.

<img width="1424" alt="스크린샷 2022-12-05 오후 6 05 18" src="https://user-images.githubusercontent.com/11639939/205597499-295a6f29-74eb-4764-bae3-1040dd796026.png">

**Comment by RoscoPColtrane1** [comment]
yes, i have this screen sir. :) 
I generated and imported a validator keystore, its running all 3 dockers (agora-cl,el,validator) but i didnt deposit yet. So im good for now.
i will do the deposit before 10 january.
i will close this issue for now, thank you.
