### ISSUE TITLE
validator node setup

### ISSUE THREAD

**Issue by dyun18** [bosagora/agora-chain#43]
Hi I'm trying to setup a validator node on AWS.  I’m very illiterate about server related matters.  I followed the video instructions exactly as explained. but I need your help.
This is what I did so far.
1.  I signed up for an AWS free account.
2.  I followed video instructions and configured the AWS EC2 instances exactly as your main-net setup videos.
3.  Updated and the docker-engine installed
4.  Agora-chain main-net unzipped.
5.  Execution layer
Init execution node done
I ran execution node. But it did not end up like what I see on the video. Please see the screen shot.  “chain is post-merge, waiting for beacon client sync switch-over..”
“Snapshot extension registration failed   peer=cbd3f861 err="peer connected on snap without compatible eth support"

Let me know if need to run “  ./agora.sh el-node run” it again or whatever is needed to go next step.

6.  Did not run Consensus Layer or any step after that.
7.  I did generate and saved the key and validator files.
I appreciate your help.
![photo_2023-04-11_23-00-43](https://user-images.githubusercontent.com/130155197/231187404-046e1e72-7a42-4eec-9a41-5c13ed6d41f4.jpg)
![Boa-mainet](https://user-images.githubusercontent.com/130155197/231187699-8ea8bda8-a073-4306-9333-68294c24da80.png)

**Comment by TrustHenry** [comment]
The video was taken before the merge, and the output log is different.
The execution node log in the screenshot is waiting for merge.
Currently, blocks are being created at the consensus layer after merging.
When the consensus layer is executed, it will move forward.
Have a nice day.

**Comment by MichaelKim20** [comment]
@dyun18 
Run Agora-cl-node, the consensus layer.
Please refer to the document below and proceed
https://github.com/bosagora/agora-chain/blob/v0.x.x/docs/INSTALL-NODE-UBUNTU-EN.md#7-running-agora-cl-node
Agora-el-node, Agora-cl-node must run together.
