### ISSUE TITLE
mainnet upgrade from mainnet-v1.0.0 to agora-chain/v0.x.x/upgrade.sh

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/agora-chain#86]
Hi, Im still running the first dockers from (https://github.com/bosagora/agora-chain/releases/tag/mainnet-v1.0.0).

The new upgrade.sh file creates a different directory tree for the imported validators than the old version. How do i move my current validators? With this file 'all-accounts.keystore.json'?
 
old path: /bosagora/agora-chain-mainnet/root/wallet/direct/accounts/all-accounts.keystore.json
new path: /bosagora/agora-chain/networks/mainnet/root/wallet/direct/accounts/all-accounts.keystore.json

Wich steps do i take to upgrade with my current active validators into the new directory tree (without getting slashed). ;)

I there an easy way? stop all old containers, then build/install the new tree for mainnet and then move (not copy) the all-accounts.keystore.json file to the new location? and delete the old tree?

Or do i need to destroy it the old wallet, install the new tree, create a new wallet and manually import the validators again into the new wallet on the new location?
Are these the instructions i need?: https://agora-cl-docs.bosagora.org/docs/advanced/migrating-keys (move to a new machine)

Please advise,
Thx, Rosco.

**Comment by RoscoPColtrane1** [comment]
NeverMind, i started a clean install.

This upgrade script: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/bosagora/agora-chain/v0.x.x/upgrade.sh)" gave me errors in mainnet syncing, so i deleted the chain ./networks/mainnet/root/chain and started over. Without the upgrade-script it syncs well.  The upgrade script is for later i guess?

After the sync i imported the key-store files and i runs fine now.
I deleted the old directory so i cant run both validators by mistake and get slashed.

**Comment by RoscoPColtrane1** [comment]
I started a new install: https://github.com/bosagora/agora-chain#install-for-linux-or-macos 
and manually imported the keystore-files again. I will delete the old validator directory later so it wont get slashed.

Synced it 3 times from the beginning with separate windows ./agora.sh el-node run and ./agora.sh cl-node run. 
After i ran 'docker-compose-up' the nodes gave errors in docker logs. 
First i thought it was the chain but then I noticed i need /bosagora/agora-chain/agora.sh docker-compose up

The errors below apear when I use the 'wrong' agora.sh in a different path:
/bosagora/agora-chain/networks/mainnet/agora.sh docker-compose up

I will let it run for the night. Hopefully its more prepared when the withdraw-update is live. 
When the upgrade is live i only need to do `/bosagora/agora-chain/agora.sh upgrade` i hope?

logs when using the wrong agora.sh:
validator:
time="2023-07-14 20:38:01" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2023-07-14 20:38:01" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator

agora-cl:
time="2023-07-14 20:38:56" level=warning msg="Block is not processed" error="could not process block: could not execute state transition: could not validate state root, wanted: 0x9a4...., received: 0x7fd....." prefix=initial-sync
time="2023-07-14 20:38:56" level=info msg="Processing block 0xad803d17... 1328160/1328233 - estimated time remaining 15s" blocksPerSecond=4.7 peers=46 prefix=initial-sync
time="2023-07-14 20:39:01" level=warning msg="Execution client is not syncing" prefix=powchain

agora-el:
WARN [07-14|20:37:19.866] Snapshot extension registration failed   peer=f5aae61a err="peer connected on snap without compatible eth support"
WARN [07-14|20:38:33.180] Snapshot extension registration failed   peer=bfaaa73a err="peer connected on snap without compatible eth support"
WARN [07-14|20:39:44.716] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!

**Comment by RoscoPColtrane1** [comment]
still get these errors after 4 or 6 epochs, the nodes trow errors and get offline.
Only the old version works for now.

node-el
INFO [07-14|22:01:17.234] Chain head was updated                   number=2,505,940 hash=183b65..9c15ca root=8eb456..aab455 elapsed="88.279µs"
WARN [07-14|22:03:21.706] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!

node-cl:
time="2023-07-14 22:01:29" level=error msg="Could not handle p2p pubsub" error="could not process block: could not execute state transition: could not validate state root, wanted: 0xaf18...., received: 0x6632...." prefix=sync topic="/eth2/868b726f/beacon_block/ssz_snappy"
time="2023-07-14 22:13:05" level=info msg="Subscribed to topic" prefix=sync topic="/eth2/868b726f/beacon_attestation_23/ssz_snappy"
time="2023-07-14 22:13:08" level=warning msg="Execution client is not syncing" prefix=powchain

validator:
time="2023-07-14 22:16:25" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator pubKey=0xa...

**Comment by RoscoPColtrane1** [comment]
Since I get the same messages everywhere, are the new scripts useable for mainnet? Or do i have to wait a bit longer?

**Comment by RoscoPColtrane1** [comment]
Ok, i tried again, deleted the database and (./agora cl-node clear-db) and ran .../v0.x.x/upgrade.sh
I did a full sync of el-node and cl-node in separate terminals.
After that i started the validator in a terminal for 30 minutes. it stayed stable.
Then i closed all terminals and did ./agora.sh docker-compose up
They all ran fine in the background.
Then i noticed when i stop the nodes (./agora.sh docker-compose down) and change the dir name from 'agora-chain-new' to 'agora-chain' the errors come back.

I installed again with the same directoryname 'agora-chain', now they run fine.
Maybe there is path (pwd) written to the config files after the installation?

**Comment by RoscoPColtrane1** [comment]
After 9 epochs the nodes stop, and give errors. I cant seem to find the problem. :(
These new instructions dont work (https://bosagora.io/en/validator, https://github.com/bosagora/agora-chain#for-linux-or-macos-users). please advice

WARN [07-16|20:06:26.540] Snapshot extension registration failed   peer=3af25a30 err="peer connected on snap without compatible eth support"
WARN [07-16|20:06:54.499] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
WARN [07-16|20:09:27.937] Snapshot extension registration failed   peer=12b92df9 err="peer connected on snap without compatible eth support"
WARN [07-16|20:11:54.536] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!

time="2023-07-16 20:21:38" level=warning msg="Execution client is not syncing" prefix=powchain
time="2023-07-16 20:21:39" level=info msg="Processing block 0x630fa930... 1342464/1342546 - estimated time remaining 8s" blocksPerSecond=9.7 peers=47 prefix=initial-sync

time="2023-07-16 20:23:13" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2023-07-16 20:23:21" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2023-07-16 20:23:25" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator

**Comment by MichaelKim20** [comment]
Mainnet is not ready for upgrade yet.
We will notify the community when our preparations are complete.

**Comment by RoscoPColtrane1** [comment]
Aah, then its not me :) 
All the webpages of the Bosagora website forward to the new mainnet github pages, so that confused me.
Thx Michael.

**Comment by MichaelKim20** [comment]
> Hi, Im still running the first dockers from (https://github.com/bosagora/agora-chain/releases/tag/mainnet-v1.0.0).
> 
> The new upgrade.sh file creates a different directory tree for the imported validators than the old version. How do i move my current validators? With this file 'all-accounts.keystore.json'?
> 
> old path: /bosagora/agora-chain-mainnet/root/wallet/direct/accounts/all-accounts.keystore.json new path: /bosagora/agora-chain/networks/mainnet/root/wallet/direct/accounts/all-accounts.keystore.json
> 
> Wich steps do i take to upgrade with my current active validators into the new directory tree (without getting slashed). ;)
> 
> I there an easy way? stop all old containers, then build/install the new tree for mainnet and then move (not copy) the all-accounts.keystore.json file to the new location? and delete the old tree?
> 
> Or do i need to destroy it the old wallet, install the new tree, create a new wallet and manually import the validators again into the new wallet on the new location? Are these the instructions i need?: https://agora-cl-docs.bosagora.org/docs/advanced/migrating-keys (move to a new machine)
> 
> Please advise, Thx, Rosco.

When you run upgrade.sh from a previously installed folder, the wallet is copied to the new folder.
The link below is the part of the upgrade script source that copies the previous data and wallet.

https://github.com/bosagora/agora-chain/blob/v0.x.x/upgrade.sh#L101-L108

So you don't have to run anything other than running upgrade.sh .

**Comment by MichaelKim20** [comment]
> Hi, Im still running the first dockers from (https://github.com/bosagora/agora-chain/releases/tag/mainnet-v1.0.0).
> 
> The new upgrade.sh file creates a different directory tree for the imported validators than the old version. How do i move my current validators? With this file 'all-accounts.keystore.json'?
> 
> old path: /bosagora/agora-chain-mainnet/root/wallet/direct/accounts/all-accounts.keystore.json new path: /bosagora/agora-chain/networks/mainnet/root/wallet/direct/accounts/all-accounts.keystore.json
> 
> Wich steps do i take to upgrade with my current active validators into the new directory tree (without getting slashed). ;)
> 
> I there an easy way? stop all old containers, then build/install the new tree for mainnet and then move (not copy) the all-accounts.keystore.json file to the new location? and delete the old tree?
> 
> Or do i need to destroy it the old wallet, install the new tree, create a new wallet and manually import the validators again into the new wallet on the new location? Are these the instructions i need?: https://agora-cl-docs.bosagora.org/docs/advanced/migrating-keys (move to a new machine)
> 
> Please advise, Thx, Rosco.

@RoscoPColtrane1 
When you run upgrade.sh from a previously installed folder, the wallet is copied to the new folder.
The link below is the part of the upgrade script source that copies the previous data and wallet.

https://github.com/bosagora/agora-chain/blob/v0.x.x/upgrade.sh#L101-L108

So you don't have to run anything other than running upgrade.sh .

**Comment by MichaelKim20** [comment]
> I started a new install: https://github.com/bosagora/agora-chain#install-for-linux-or-macos and manually imported the keystore-files again. I will delete the old validator directory later so it wont get slashed.
> 
> Synced it 3 times from the beginning with separate windows ./agora.sh el-node run and ./agora.sh cl-node run. After i ran 'docker-compose-up' the nodes gave errors in docker logs. First i thought it was the chain but then I noticed i need /bosagora/agora-chain/agora.sh docker-compose up
> 
> The errors below apear when I use the 'wrong' agora.sh in a different path: /bosagora/agora-chain/networks/mainnet/agora.sh docker-compose up
> 
> I will let it run for the night. Hopefully its more prepared when the withdraw-update is live. When the upgrade is live i only need to do `/bosagora/agora-chain/agora.sh upgrade` i hope?
> 
> logs when using the wrong agora.sh: validator: time="2023-07-14 20:38:01" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator time="2023-07-14 20:38:01" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
> 
> agora-cl: time="2023-07-14 20:38:56" level=warning msg="Block is not processed" error="could not process block: could not execute state transition: could not validate state root, wanted: 0x9a4...., received: 0x7fd....." prefix=initial-sync time="2023-07-14 20:38:56" level=info msg="Processing block 0xad803d17... 1328160/1328233 - estimated time remaining 15s" blocksPerSecond=4.7 peers=46 prefix=initial-sync time="2023-07-14 20:39:01" level=warning msg="Execution client is not syncing" prefix=powchain
> 
> agora-el: WARN [07-14|20:37:19.866] Snapshot extension registration failed peer=f5aae61a err="peer connected on snap without compatible eth support" WARN [07-14|20:38:33.180] Snapshot extension registration failed peer=bfaaa73a err="peer connected on snap without compatible eth support" WARN [07-14|20:39:44.716] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!



> I started a new install: https://github.com/bosagora/agora-chain#install-for-linux-or-macos and manually imported the keystore-files again. I will delete the old validator directory later so it wont get slashed.
> 
> Synced it 3 times from the beginning with separate windows ./agora.sh el-node run and ./agora.sh cl-node run. After i ran 'docker-compose-up' the nodes gave errors in docker logs. First i thought it was the chain but then I noticed i need /bosagora/agora-chain/agora.sh docker-compose up
> 
> The errors below apear when I use the 'wrong' agora.sh in a different path: /bosagora/agora-chain/networks/mainnet/agora.sh docker-compose up
> 
> I will let it run for the night. Hopefully its more prepared when the withdraw-update is live. When the upgrade is live i only need to do `/bosagora/agora-chain/agora.sh upgrade` i hope?
> 
> logs when using the wrong agora.sh: validator: time="2023-07-14 20:38:01" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator time="2023-07-14 20:38:01" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
> 
> agora-cl: time="2023-07-14 20:38:56" level=warning msg="Block is not processed" error="could not process block: could not execute state transition: could not validate state root, wanted: 0x9a4...., received: 0x7fd....." prefix=initial-sync time="2023-07-14 20:38:56" level=info msg="Processing block 0xad803d17... 1328160/1328233 - estimated time remaining 15s" blocksPerSecond=4.7 peers=46 prefix=initial-sync time="2023-07-14 20:39:01" level=warning msg="Execution client is not syncing" prefix=powchain
> 
> agora-el: WARN [07-14|20:37:19.866] Snapshot extension registration failed peer=f5aae61a err="peer connected on snap without compatible eth support" WARN [07-14|20:38:33.180] Snapshot extension registration failed peer=bfaaa73a err="peer connected on snap without compatible eth support" WARN [07-14|20:39:44.716] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!

----
If you are directly under the folder agora-chain/,
You should just run ./agora.sh . Then various commands will find the network and enter it.
Before you do that, you should prepare to use the mainnet using the following command.

https://github.com/bosagora/agora-chain#install-for-linux-or-macos
```
./agora.sh network mainnet
```

**Comment by MichaelKim20** [comment]
> still get these errors after 4 or 6 epochs, the nodes trow errors and get offline. Only the old version works for now.
> 
> node-el INFO [07-14|22:01:17.234] Chain head was updated number=2,505,940 hash=183b65..9c15ca root=8eb456..aab455 elapsed="88.279µs" WARN [07-14|22:03:21.706] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
> 
> node-cl: time="2023-07-14 22:01:29" level=error msg="Could not handle p2p pubsub" error="could not process block: could not execute state transition: could not validate state root, wanted: 0xaf18...., received: 0x6632...." prefix=sync topic="/eth2/868b726f/beacon_block/ssz_snappy" time="2023-07-14 22:13:05" level=info msg="Subscribed to topic" prefix=sync topic="/eth2/868b726f/beacon_attestation_23/ssz_snappy" time="2023-07-14 22:13:08" level=warning msg="Execution client is not syncing" prefix=powchain
> 
> validator: time="2023-07-14 22:16:25" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator pubKey=0xa...

**Comment by MichaelKim20** [comment]
> still get these errors after 4 or 6 epochs, the nodes trow errors and get offline. Only the old version works for now.
> 
> node-el INFO [07-14|22:01:17.234] Chain head was updated number=2,505,940 hash=183b65..9c15ca root=8eb456..aab455 elapsed="88.279µs" WARN [07-14|22:03:21.706] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
> 
> node-cl: time="2023-07-14 22:01:29" level=error msg="Could not handle p2p pubsub" error="could not process block: could not execute state transition: could not validate state root, wanted: 0xaf18...., received: 0x6632...." prefix=sync topic="/eth2/868b726f/beacon_block/ssz_snappy" time="2023-07-14 22:13:05" level=info msg="Subscribed to topic" prefix=sync topic="/eth2/868b726f/beacon_attestation_23/ssz_snappy" time="2023-07-14 22:13:08" level=warning msg="Execution client is not syncing" prefix=powchain
> 
> validator: time="2023-07-14 22:16:25" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator pubKey=0xa...

### I just did two tests.
1. Upgraded agora-chain to a new version.
2. Started a new agora-chain for the first time
I succeeded in both tests.

I guess there are the following reasons for your failure.
1. When some of the commands have not been executed
2. When running on a different path
3. ./agora.sh el-node init is not executed
4. After the accidental first failure you have to delete all the data and start over.
  ```
  ./agora.sh el-node init
  ./agora.sh cl-node clear-db
  ```

Do it in the following order

### 1. On initial installation
```
mkdir agora-chain
cd agora-chain
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/bosagora/agora-chain/v0.x.x/agora.sh)"
./agora.sh network mainnet
./agora.sh el-node init
./agora.sh el-node run
```
at another terminal
```
./agora.sh cl-node run
```

 ### 2. When you upgrade
```
cd agora-chain # (or cd agora-chain-main)
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/bosagora/agora-chain/v0.x.x/upgrade.sh)"
./agora.sh network mainnet  # If it's the mainnet, you can skip it.
./agora.sh docker-compose up
```

**Comment by RoscoPColtrane1** [comment]
> Mainnet is not ready for upgrade yet. We will notify the community when our preparations are complete.

Testnet works with no problems, Mainnet looks ok, but only for a few epochs. It wont last long. Try to stop it and start it as docker-compose or reboot. 

The el-node seems to stop communicating after i bring it back up or after a while. The other nodes trow errors (Please fix your beacon client to follow the chain!) .. i did exactly what you discibed in no.1.

But the mainnet preparations are not complete yet. Maybe thats it, thats the reason i get errors.

**Comment by RoscoPColtrane1** [comment]
Mainnet runs fine till about 5 epochs. This is the logging where the nodes stop functioning:

log el-node:

INFO [07-17|16:31:41.350] Imported new potential chain segment     number=2,525,855 hash=5bb664..04bc90 blocks=1 txs=0 mgas=0.000 elapsed="772.584µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:31:41.358] Chain head was updated                   number=2,525,855 hash=5bb664..04bc90 root=015505..82aab1 elapsed="108.603µs"
INFO [07-17|16:31:53.217] Imported new potential chain segment     number=2,525,856 hash=e7550b..f4a354 blocks=1 txs=0 mgas=0.000 elapsed="778.661µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:31:53.224] Chain head was updated                   number=2,525,856 hash=e7550b..f4a354 root=df72d3..622367 elapsed="95.403µs"
INFO [07-17|16:32:05.354] Imported new potential chain segment     number=2,525,857 hash=2bf387..ecdbb3 blocks=1 txs=0 mgas=0.000 elapsed="775.029µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:32:05.361] Chain head was updated                   number=2,525,857 hash=2bf387..ecdbb3 root=e1bcbb..76751f elapsed="72.915µs"
WARN [07-17|16:32:08.831] Snapshot extension registration failed   peer=1d4fc8e3 err="peer connected on snap without compatible eth support"
INFO [07-17|16:32:17.161] Imported new potential chain segment     number=2,525,858 hash=ccbfde..12c8ca blocks=1 txs=0 mgas=0.000 elapsed="767.207µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:32:17.169] Chain head was updated                   number=2,525,858 hash=ccbfde..12c8ca root=756071..19e534 elapsed="83.461µs"
WARN [07-17|16:32:28.507] Snapshot extension registration failed   peer=d8de3349 err="peer connected on snap without compatible eth support"
INFO [07-17|16:32:29.194] Imported new potential chain segment     number=2,525,859 hash=07ec35..1c5728 blocks=1 txs=0 mgas=0.000 elapsed="827.969µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:32:29.200] Chain head was updated                   number=2,525,859 hash=07ec35..1c5728 root=0c3a67..8473d3 elapsed="93.447µs"
INFO [07-17|16:32:41.247] Imported new potential chain segment     number=2,525,860 hash=d1f257..a6b889 blocks=1 txs=0 mgas=0.000 elapsed=1.065ms     mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:32:41.254] Chain head was updated                   number=2,525,860 hash=d1f257..a6b889 root=e4f446..f49f1a elapsed="86.674µs"
INFO [07-17|16:32:53.151] Imported new potential chain segment     number=2,525,861 hash=2ad239..35945d blocks=1 txs=0 mgas=0.000 elapsed="850.457µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:32:53.159] Chain head was updated                   number=2,525,861 hash=2ad239..35945d root=2665c6..c4a7d9 elapsed="85.415µs"
INFO [07-17|16:33:05.379] Imported new potential chain segment     number=2,525,862 hash=c97206..8f9e3b blocks=1 txs=0 mgas=0.000 elapsed="769.372µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:33:05.386] Chain head was updated                   number=2,525,862 hash=c97206..8f9e3b root=7de50d..4d3ded elapsed="83.53µs"
INFO [07-17|16:33:17.189] Imported new potential chain segment     number=2,525,863 hash=df8e30..32b4dc blocks=1 txs=0 mgas=0.000 elapsed="878.673µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:33:17.196] Chain head was updated                   number=2,525,863 hash=df8e30..32b4dc root=3521f9..0a9fa0 elapsed="128.996µs"
INFO [07-17|16:33:29.239] Imported new potential chain segment     number=2,525,864 hash=f5ae30..3085f2 blocks=1 txs=0 mgas=0.000 elapsed="757.359µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:33:29.247] Chain head was updated                   number=2,525,864 hash=f5ae30..3085f2 root=4ca677..373f18 elapsed="103.924µs"
INFO [07-17|16:33:41.212] Imported new potential chain segment     number=2,525,865 hash=16b0de..ff736d blocks=1 txs=0 mgas=0.000 elapsed="894.807µs" mgasps=0.000 dirty=289.50KiB
INFO [07-17|16:33:41.219] Chain head was updated                   number=2,525,865 hash=16b0de..ff736d root=f04a9d..dc8e6c elapsed="53.847µs"
**WARN [07-17|16:35:43.398] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
WARN [07-17|16:39:22.559] Snapshot extension registration failed   peer=0daa5b20 err="peer connected on snap without compatible eth support"**

agora cl-node:

time="2023-07-17 16:32:17" level=info msg="Synced new block" block=0x9998ddb2... epoch=42143 finalizedEpoch=42141 finalizedRoot=0x3c18950d... prefix=blockchain slot=1348600
time="2023-07-17 16:32:17" level=info msg="Finished applying state transition" attestations=1 payloadHash=0xccbfde0b6b1a prefix=blockchain slot=1348600 syncBitsCount=512 txCount=0
time="2023-07-17 16:32:29" level=info msg="Synced new block" block=0xef6cbba4... epoch=42143 finalizedEpoch=42141 finalizedRoot=0x3c18950d... prefix=blockchain slot=1348601
time="2023-07-17 16:32:29" level=info msg="Finished applying state transition" attestations=1 payloadHash=0x07ec356a7397 prefix=blockchain slot=1348601 syncBitsCount=512 txCount=0
time="2023-07-17 16:32:41" level=info msg="Synced new block" block=0x8be91d23... epoch=42143 finalizedEpoch=42141 finalizedRoot=0x3c18950d... prefix=blockchain slot=1348602
time="2023-07-17 16:32:41" level=info msg="Finished applying state transition" attestations=1 payloadHash=0xd1f2578e42f1 prefix=blockchain slot=1348602 syncBitsCount=512 txCount=0
time="2023-07-17 16:32:53" level=info msg="Synced new block" block=0x482ba6d5... epoch=42143 finalizedEpoch=42141 finalizedRoot=0x3c18950d... prefix=blockchain slot=1348603
time="2023-07-17 16:32:53" level=info msg="Finished applying state transition" attestations=1 payloadHash=0x2ad2391780a0 prefix=blockchain slot=1348603 syncBitsCount=512 txCount=0
time="2023-07-17 16:33:01" level=info msg="Peer summary" activePeers=48 inbound=13 outbound=35 prefix=p2p
time="2023-07-17 16:33:05" level=info msg="Synced new block" block=0x62dd0b8f... epoch=42143 finalizedEpoch=42141 finalizedRoot=0x3c18950d... prefix=blockchain slot=1348604
time="2023-07-17 16:33:05" level=info msg="Finished applying state transition" attestations=1 payloadHash=0xc97206a34572 prefix=blockchain slot=1348604 syncBitsCount=512 txCount=0
time="2023-07-17 16:33:17" level=info msg="Synced new block" block=0x722e534d... epoch=42143 finalizedEpoch=42141 finalizedRoot=0x3c18950d... prefix=blockchain slot=1348605
time="2023-07-17 16:33:17" level=info msg="Finished applying state transition" attestations=1 payloadHash=0xdf8e30860d92 prefix=blockchain slot=1348605 syncBitsCount=512 txCount=0
time="2023-07-17 16:33:29" level=info msg="Synced new block" block=0x156cb803... epoch=42143 finalizedEpoch=42141 finalizedRoot=0x3c18950d... prefix=blockchain slot=1348606
time="2023-07-17 16:33:29" level=info msg="Finished applying state transition" attestations=1 payloadHash=0xf5ae30f00383 prefix=blockchain slot=1348606 syncBitsCount=512 txCount=0
time="2023-07-17 16:33:41" level=info msg="Synced new block" block=0x190d19fb... epoch=42143 finalizedEpoch=42141 finalizedRoot=0x3c18950d... prefix=blockchain slot=1348607
time="2023-07-17 16:33:41" level=info msg="Finished applying state transition" attestations=1 payloadHash=0x16b0de9fea0d prefix=blockchain slot=1348607 syncBitsCount=512 txCount=0
**time="2023-07-17 16:33:53" level=warning msg="rate is 0, skipping initializing topic scoring" prefix=p2p
time="2023-07-17 16:33:53" level=info msg="Subscribed to topic" prefix=sync topic="/eth2/868b726f/beacon_attestation_11/ssz_snappy"
time="2023-07-17 16:33:53" level=warning msg="rate is 0, skipping initializing topic scoring" prefix=p2p
time="2023-07-17 16:33:53" level=info msg="Subscribed to topic" prefix=sync topic="/eth2/868b726f/beacon_attestation_20/ssz_snappy"**
**time="2023-07-17 16:33:53" level=error msg="Could not handle p2p pubsub" error="could not process block: could not execute state transition: could not validate state root, wanted: 0x75d16b23d9e6b5d181d6eca81c499235deac6598f1cd559df986b12e4f5bc0b1, received: 0xa0c3e68d882e4ae0e1a685235a882f8bc9c309b76f7e1262b33cd7e6320141c5" prefix=sync topic="/eth2/868b726f/beacon_block/ssz_snappy"**
time="2023-07-17 16:34:01" level=info msg="Peer summary" activePeers=46 inbound=11 outbound=35 prefix=p2p
time="2023-07-17 16:35:01" level=info msg="Peer summary" activePeers=45 inbound=11 outbound=34 prefix=p2p
time="2023-07-17 16:36:01" level=info msg="Peer summary" activePeers=45 inbound=11 outbound=34 prefix=p2p
time="2023-07-17 16:37:01" level=info msg="Peer summary" activePeers=45 inbound=11 outbound=34 prefix=p2p
time="2023-07-17 16:38:01" level=info msg="Peer summary" activePeers=44 inbound=11 outbound=33 prefix=p2p
time="2023-07-17 16:38:48" level=warning msg="Execution client is not syncing" prefix=powchain
time="2023-07-17 16:39:01" level=info msg="Peer summary" activePeers=48 inbound=11 outbound=37 prefix=p2p
time="2023-07-17 16:39:02" level=warning msg="Execution client is not syncing" prefix=powchain

**Comment by RoscoPColtrane1** [comment]
The 3 new node versions (v2.0.1) fixed it, i used these commands:
./agora.sh el-node init
./agora.sh cl-node clear-db
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/bosagora/agora-chain/v0.x.x/upgrade.sh)"
./agora.sh cl-node run
./agora.sh el-node run (another terminal)
After full sync, i stopped cl-node and el-node and ran:
./agora.sh docker-compose up
Docker logging runs fine now, no beacon-client errors.
