### ISSUE TITLE
proposer_config.json fee adress = voter adress?

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/agora-chain#87]
Hi the instruction on ./networks/mainnet/root/config/cl/proposer_config.json file on youtube is different then the online manual.

Here they open the voter-file and copy the voter-adress:
[https://youtu.be/Gkfn2Aq0_n8?t=616](url)

Here they use the wallet adress you want to send the fees to:
[https://docs.prylabs.network/docs/execution-node/fee-recipient](url)

1. Which adress is the right fee-adres? voter- or walletadress?
2. When i have multiple nodes, is this the format of the file?:

{
  "proposer_config": {
    "0x[PUBLIC_KEY_1]": {
      "fee_recipient": "WALLET_ADRESS?"
    },
    "0x[PUBLIC_KEY_2]": {
      "fee_recipient": "WALLET_ADRESS?"
    },
    "0x[PUBLIC_KEY_3]": {
      "fee_recipient": "WALLET_ADRESS?"
    },
    "0x[PUBLIC_KEY_4]": {
      "fee_recipient": "WALLET_ADRESS?"
    }
  },
  "default_config": {
    "fee_recipient": "WALLET_ADRESS?"
  }
}
thx!

**Comment by MichaelKim20** [comment]
You're the only one who has Wallet's private key.
The voting wallet is the wallet created to use Votera and is associated with the key of the validator.
Therefore, you can use the voting wallet, or you can use the address of the wallet you already have.

**Comment by RoscoPColtrane1** [comment]
So its better to associate the voter adress with the public key and use the wallet adres as the 'default_config'?
like this:

{
"proposer_config": {
"0x[PUBLIC_KEY_1]": {
"fee_recipient": "VOTER_ADRESS"
},
"0x[PUBLIC_KEY_2]": {
"fee_recipient": "VOTER_ADRESS"
},
"0x[PUBLIC_KEY_3]": {
"fee_recipient": "VOTER_ADRESS"
},
"0x[PUBLIC_KEY_4]": {
"fee_recipient": "VOTER_ADRESS"
}
},
"default_config": {
"fee_recipient": "WALLET_ADRESS?"
}
}

**Comment by MichaelKim20** [comment]
This is the easiest way
``` JSON
{
  "proposer_config": {
  },
  "default_config": {
    "fee_recipient": "YOUR_WALLET_ADRESS"
  }
}
```

**Comment by RoscoPColtrane1** [comment]
i will try this, thanks.
