### ISSUE TITLE
BizNet to Ethereum mainnet Bridge 후에 BOA 잔고가 사라짐 / BizNet to Ethereum mainnet Bridge - BOA Balance Disappeared

### ISSUE THREAD

**Issue by hwooson12** [bosagora/agora-chain#99]
안녕하세요 어디에 문의를 남겨야 할지 몰라서 여기에 남깁니다. 

https://boaswap.io/bridge 에서 BOSAgora mainnet(BizNet)에 있는 BOA를 거래소에 옮기기 위해 Ethereum mainnet으로 옮기는 작업을 했는데 트랜잭션에 성공했지만 잔고가 Ethereum mainnet에 들어오지 않습니다. 해당 트랜젝션은 https://boascan.io/tx/0xcdaf4c7afacae54a32772bbe3d74d52b42cb2b6a4c8daeef167f56989422ff48/internal-transactions 인데 확인 부탁드립니다.

Hello, I am not sure where to post this, so I am leaving my inquiry here.

I was transferring BOA from BOSAgora mainnet (BizNet) at https://boaswap.io/bridge to an exchange, and for this purpose, I used the bridge to move it to the Ethereum mainnet. The transaction was successful, but the balance has not appeared in the Ethereum mainnet. The transaction in question can be found at https://boascan.io/tx/0xcdaf4c7afacae54a32772bbe3d74d52b42cb2b6a4c8daeef167f56989422ff48/internal-transactions. Could you please check on this?

cc. @MichaelKim20 @TrustHenry

**Comment by TrustHenry** [comment]
안녕하세요. 
https://boaswap.io/bridge 에서  From BOSAgora mainnet(BizNet) -> To Ethereum mainnet 으로 아토믹스왑 오픈은 트랜잭션 으로 확인 됩니다.
BOASwap 진행중에 모달창을 빠르게 닫으셨는지요? TxId 가 제출되지 않은것 같습니다.
BOASwap Bridge 화면의 오른쪽 상단의 Recent Transactions 내역을 보시고 상태값을 알려주시면 좀더 자세히 알 수 있을것 같습니다.
또는 지갑을 연결하고 Bridge화면에서 대기하면 로컬스토리지에 저장된 TxId 를 자동제출 합니다.

**Comment by hwooson12** [comment]
Recent transaction에는 아무것도 나오지 않고 메타마스크 활동 기록에는 아래와 같이 나오네요

<img width="301" alt="image" src="https://github.com/bosagora/agora-chain/assets/16971553/03432d29-b20a-427e-99d6-6269f1deeae8">

Swap 진행할 때 pending 이후에 완료된 거 확인하고 창을 닫았는데 어떤 정보를 더 확인해볼 수 있을까요?

**Comment by TrustHenry** [comment]
해당 트랜잭션은 사용자의 클라이언트 작업중단으로 브릿지 아토믹 스왑 과정이 더이상 진행 되지 않았습니다.
이 트랜잭션의 결과를 되돌리기 위해서는 실행 시점으로 24시간후 해당 입금을 취소 할 수 있습니다.
이 방법은 BOASwap Recent Transactions 에서 내역별로 UI에서 Cancel 버튼을 제공 하고 있으며 사용자는 이 Cancel 버튼으로
컨트랙트 expireDeposit 실행을 통해 입금 금액을 돌려 받을 수 있습니다. (소량의 트랜잭션 가스피가 소모 됩니다.)
만약 사용자가 Recent Transactions  화면에서 Clear all 버튼을 눌러 내역을 삭제 했다면 UI를 통해서 취소 할 수 없습니다.
그렇다면 스마트 컨트랙트를 직접 실행 하는 트랜잭션을 사용자가 발생 시켜야 합니다.
호출 해야할 스마트 컨트랙트 의 함수를 안내 드립니다.

Contract Addess : 0x95075eDc815e9Cd62Ff6D4598ea922307416B452

expireDeposit(bytes32 _boxID)

https://github.com/bosagora/bizboa-bridge-contracts/blob/2aeec769ecede83f59cfda2a143eb342c7ea1e51/contracts/bridge/BOACoinBridge.sol#L171

**Comment by hwooson12** [comment]
@TrustHenry 

답변 감사합니다!! 그런데 제가 이쪽 분야 개발 경험이 없어서 말씀해주신 스마트 컨트랙트를 직접 실행한느 트랜잭션 발생하는 부분에 관해 참고할만한 문서가 있을까요? 제가 찾은건 https://docs.bosagora.org/en/getting-started/deploy-smart-contract 이건데 혹시 참고할만한 문서가 있으면 알려주시면 감사하겠습니다! 그리고 저 함수의 _boxID는 어떤 값을 넣으면 되는건지도 궁금하네요. 저 함수를 실행하기 위해 필요한 값들이 뭐가 있는지도 간단히 설명부탁드립니다! 다시 한 번 도와주셔서 정말 감사해요!

**Comment by MichaelKim20** [comment]
@hwooson12 
브릿지를 호출한 후 키를 전달해야 하는데, 이것이 진행되기 전에 브라우즈를 닫으신것 같습니다.
해당키는 랜덤으로 생성되는 것이라 사용하신 브라우즈의 로컬저장소에 저장되어 있을 것 같습니다.
저의 텔레그램 아이디는 worldia20 입니다. 텔레그램으로 연락부탁드립니다.

**Comment by MichaelKim20** [comment]
Returned assets using bridge function expireDeposit.
And again, we successfully exchanged the boa token on Ethernet using the bridge.
